import rrule

r = rrule.fromUserInput('20 days')
print(r)
r = rrule.toStr(r)
print(r)
r = rrule.fromUserInput('1 weeks on mon,thu')
print(r)
r = rrule.toStr(r)
print(r)
r = rrule.fromUserInput('3 days for 15 times')
print(r)
r = rrule.toStr(r)
print(r)
r = rrule.fromUserInput('2 weeks on fri until 31 12 2019')
print(r)
r = rrule.toStr(r)
print(r)